version: '3'

services:
    meme-bot:
        build: .
        image: ropc/meme-bot:latest
        container_name: meme-bot
        volumes:
            - memebot:/code
        environment:
            REMINDERS_SAVE_FILE_PATH: /code/reminders.pickle
            WHISPER_CONFIG_FILE_PATH: /code/whisper_config.json
            OOC_CONFIG_FILE_PATH: /code/ooc_config.json

volumes:
  memebot:
