version: '3'

services:
    meme-bot:
        env_file:
            - debug.env
        command: [ "memebot.memebot", "run_debug" ]
        ports:
            - "5678:5678"
    meme-bot-rust:
        env_file:
            - debug.env
