[tool.poetry]
name = "meme-bot"
version = "0.1.0"
description = ""
authors = ["ropc <itslikeroar2412@gmail.com>"]
packages = [
    { include = "apps" }
]

[tool.poetry.scripts]
bot = "apps.bot.memebot:run"
bot-debug = "apps.bot.memebot:run_debug"

[tool.poetry.dependencies]
python = "^3.7"
"discord.py" = {extras = ["voice"], version = "^1.2.5"}
pillow = "^6.1"
pygtrie = "^2.3"
pydantic = "^1.1"
youtube-dl = "^2020.3.24"
lxml = "^4.5.0"

[tool.poetry.dev-dependencies]
ipython = "^7.7"
rope = "^0.14.0"
ptvsd = "^4.3.2"
mypy = "^0.740"
requests = "^2.23.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
