[tool.poetry]
name = "memebot"
version = "0.1.0"
description = ""
authors = ["ropc <itslikeroar2412@gmail.com>"]
packages = [
    { include = "memebot" },
    { include = "meme_generator" },
]

[tool.poetry.scripts]
bot = "memebot.memebot:run"
bot-debug = "memebot.memebot:run_debug"
meme = "meme_generator.run:run_meme"

[tool.poetry.dependencies]
python = "^3.8"
"discord.py" = {extras = ["voice"], version = "^1.7.3"}
pillow = "^9.1"
pygtrie = "^2.3"
pydantic = "^1.9"
youtube-dl = "^2021.12.17"
lxml = "^4.9.0"
matplotlib = "^3.5.2"
ptvsd = "^4.3.2"
tailer = "^0.4.1"
python-dateutil = "^2.8.2"
dateparser = "^1.1.1"

[tool.poetry.dev-dependencies]
ipython = "^8.4"
rope = "^1.1.1"
mypy = "^0.961"
requests = "^2.27.1"
pytest = "^7.1.2"
pytest-asyncio = "^0.18.3"
jedi = "0.17.2"
parso = "0.7.1"

[build-system]
requires = ["poetry>=1.0.3"]
build-backend = "poetry.masonry.api"
