[tool.poetry]
name = "meme-bot"
version = "0.1.0"
description = ""
authors = ["ropc <itslikeroar2412@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
"discord.py" = "^1.2"
pillow = "^6.1"
attrs = "^19.1"
pygtrie = "^2.3"

[tool.poetry.dev-dependencies]
ipython = "^7.7"
pylint = "^2.3"
rope = "^0.14.0"
ptvsd = "^4.3.2" 

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
