[tool.poetry]
name = "memebot"
version = "0.1.0"
description = ""
authors = ["ropc <itslikeroar2412@gmail.com>"]
packages = [
    { include = "memebot" },
    { include = "meme_generator" },
]

[tool.poetry.scripts]
bot = "memebot.memebot:run"
bot-debug = "memebot.memebot:run_debug"
meme = "meme_generator.run:run_meme"

[tool.poetry.dependencies]
python = "^3.8"
"discord.py" = {extras = ["voice"], version = "^1.2.5"}
pillow = "^8.1"
pygtrie = "^2.3"
pydantic = "^1.1"
youtube-dl = "^2020.11.12"
lxml = "^4.5.0"
matplotlib = "^3.2.1"
ptvsd = "^4.3.2"
tailer = "^0.4.1"
python-dateutil = "^2.8.1"
dateparser = "^1.0.0"

[tool.poetry.dev-dependencies]
ipython = "^7.7"
rope = "^0.18.0"
mypy = "^0.780"
requests = "^2.23.0"
pytest = "^5.4.1"
pytest-asyncio = "^0.14.0"
jedi = "0.17.2"
parso = "0.7.1"

[build-system]
requires = ["poetry>=1.0.3"]
build-backend = "poetry.masonry.api"
