# This is a basic workflow to help you get started with Actions

name: CI-2

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches-ignore:
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # this decrypts the ssh key and stores it in $HOME/secrets/githubaction-key.pem
    # maybe we should add a step to delete after deploying?
    - name: Decrypt ssh key
      env:
        SSH_KEY_PASSPHRASE: ${{ secrets.SSH_KEY_PASSPHRASE }}
        REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
      run: $GITHUB_WORKSPACE/.github/scripts/decrypt_secret.sh

    - name: SSH into remote computer
      env:
        SSH_DESTINATION: ${{ secrets.SSH_DESTINATION }}
        REMOTE_DIR: ${{ secrets.REMOTE_DIR }}
      run: ssh -oStrictHostKeyChecking=no -T -i $HOME/secrets/githubaction-key.pem $SSH_DESTINATION "cd $REMOTE_DIR && git status"
